// Code generated by "stringer --type=Statuses"; DO NOT EDIT.

package todo

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Todo-0]
	_ = x[InProgress-1]
	_ = x[Done-2]
	_ = x[Review-3]
}

const _Statuses_name = "TodoInProgressDoneReview"

var _Statuses_index = [...]uint8{0, 4, 14, 18, 24}

func (i Statuses) String() string {
	if i < 0 || i >= Statuses(len(_Statuses_index)-1) {
		return "Statuses(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Statuses_name[_Statuses_index[i]:_Statuses_index[i+1]]
}
