basePath: /api
definitions:
  controllers.Response:
    properties:
      page:
        type: string
      payload: {}
    type: object
host: localhost:8080
info:
  contact:
    name: GitHub
    url: https://github.com/GlebSolncev/golang-modules
  description: This is a simple CRUD for TODO list
  title: Todo CRUD
  version: "1.0"
paths:
  /status:
    get:
      consumes:
      - application/json
      description: All statuses
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.Response'
      summary: All statuses
      tags:
      - status
  /todo:
    get:
      consumes:
      - application/json
      description: Get todos list with status items
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.Response'
      summary: All todos items with statuses
      tags:
      - todo
    post:
      consumes:
      - application/json
      description: Add new item to list
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.Response'
        "404":
          description: ""
      summary: Add item to todos list
      tags:
      - todo
  /todo/{ent.Todo.id}:
    get:
      consumes:
      - application/json
      description: Show item of Todos list
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.Response'
        "404":
          description: ""
      summary: Item from todos list
      tags:
      - todo
  /todo/{id}:
    post:
      consumes:
      - application/json
      description: Add new item to list
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.Response'
        "404":
          description: ""
      summary: Update item in list TODOs
      tags:
      - todo
  /todo/{id}/delete:
    get:
      consumes:
      - application/json
      description: Remove item from todos list
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.Response'
        "404":
          description: ""
      summary: Delete item from TODOs list
      tags:
      - todo
schemes:
- http
swagger: "2.0"
